namespace BE
{
    public enum Amenity
    {
        Pool,
        HotTub,
        Kitchen,
        Wifi,
        TV,
        Laundry,
        AirConditioning,
        Heating,
        Towels,
        Shampoo,
        Workspace,
        Furniture,
        Bedding,
        Breakfast,
        ClothesIron,
        Dishwasher,
        WalkInClosets,
        PrivateBathroom,
        FreeParking,
        Barbecue,
        Gym,
        ChildrensAttractions,
        PetFriendly,
        Garden,
        Patio,
        Hangers,
        Fireplace,
        BedsideOutlets,
        SmokeAlarm,
        Movies,
        Books,
        GameConsole
    }
}