namespace BE
{
    public enum Amenity
    {
        Pool,
        HotTub,
        Kitchen,
        Wifi,
        TV,
        Laundry,
        AirConditioning,
        Heating,
        Towels,
        Shampoo,
        Workspace,
        Closet,
        Bedding,
        Breakfast,
        Dishwasher,
        PrivateBathroom,
        Gym,
        FreeParking,
        PetFriendly,
        Garden,
        Patio,
        Fireplace,
        SmokeAlarm,
        BedsideOutlets,
        Balcony,
        SecuritySystem,
        HandicapAccessibility
    }
}